package components

const (
	_UNDEFINED_ = iota
	RCVR_TYPE_HANDGUN
	RCVR_TYPE_ASSAULT_WEAPON
	RCVR_TYPE_LONGARM
	RCVR_TYPE_LIGHT_SUPPORT_WEAPON
	RCVR_TYPE_HEAVY_WEAPON
	TECH_GAUSS_TECH
	TECH_ENERGY
	TECH_CONVENTIONAL
	CALLIBRE_HANDGUN_BlackPowder
	CALLIBRE_HANDGUN_Light
	CALLIBRE_HANDGUN_Medium
	CALLIBRE_HANDGUN_Heavy
	CALLIBRE_SMOOTHBORES_Small
	CALLIBRE_SMOOTHBORES_Light
	CALLIBRE_SMOOTHBORES_Standard
	CALLIBRE_SMOOTHBORES_Heavy
	CALLIBRE_LONGARM_BlackPowder
	CALLIBRE_LONGARM_Rifle_Light
	CALLIBRE_LONGARM_Rifle_Intermediate
	CALLIBRE_LONGARM_Rifle_Battle
	CALLIBRE_LONGARM_Rifle_Heavy
	CALLIBRE_LONGARM_Rifle_AntiMaterial
	CALLIBRE_LONGARM_Rifle_AntiMaterialHeavy
	CALLIBRE_SNUB
	CALLIBRE_Rocket
	CALLIBRE_GAUSS_Standard
	CALLIBRE_GAUSS_Small
	CALLIBRE_GAUSS_Enchanced
	CALLIBRE_GAUSS_Shotgun
	MECHANISM_SINGLE_SHOT
	MECHANISM_REPEATER
	MECHANISM_SEMI_AUTOMATIC
	MECHANISM_BURST_CAPABLE
	MECHANISM_FULLY_AUTOMATIC
	MECHANISM_RAPID_FIRE
	MECHANISM_VERY_RAPID_FIRE
	MECHANISM_UNDERWATER
	FEAT_func_ADVANCED_PROJECTILE_WEAPON
	FEAT_func_ACCUIRED
	FEAT_func_BULLPUP
	FEAT_func_COMPACT
	FEAT_func_COMPACT_VERY
	FEAT_func_COOLING_SYSTEM_BASIC
	FEAT_func_COOLING_SYSTEM_ADVANCED
	FEAT_func_GUIDENCE_SYSTEM
	FEAT_func_HIGH_CAPACITY
	FEAT_func_HIGH_QUALITY
	FEAT_func_INCREASED_RATE_OF_FIRE_1
	FEAT_func_INCREASED_RATE_OF_FIRE_2
	FEAT_func_INCREASED_RATE_OF_FIRE_3
	FEAT_func_INCREASED_RATE_OF_FIRE_4
	FEAT_func_INCREASED_RATE_OF_FIRE_5
	FEAT_func_INCREASED_RATE_OF_FIRE_6
	FEAT_func_LIGHTWEIGHT
	FEAT_func_LIGHTWEIGHT_EXTREME
	FEAT_func_LOW_QUALITY_1
	FEAT_func_LOW_QUALITY_2
	FEAT_func_LOW_QUALITY_3
	FEAT_func_LOW_QUALITY_4
	FEAT_func_LOW_QUALITY_5
	FEAT_func_QUICKDRAW
	FEAT_func_RECOIL_COMPENSATION_1
	FEAT_func_RECOIL_COMPENSATION_2
	FEAT_func_RUGGED
	FEAT_cap_ARMORED
	FEAT_cap_BULWARKED
	FEAT_cap_DISGUISED
	FEAT_cap_STEALTH_BASIC
	FEAT_cap_STEALTH_EXTREME
	FEAT_cap_VACUUM
	AMMUNITION_CAPACITY_50PCT_LESS
	AMMUNITION_CAPACITY_40PCT_LESS
	AMMUNITION_CAPACITY_30PCT_LESS
	AMMUNITION_CAPACITY_20PCT_LESS
	AMMUNITION_CAPACITY_10PCT_LESS
	AMMUNITION_CAPACITY_STANDARD
	AMMUNITION_CAPACITY_10PCT_MORE
	AMMUNITION_CAPACITY_20PCT_MORE
	AMMUNITION_CAPACITY_30PCT_MORE
	AMMUNITION_CAPACITY_40PCT_MORE
	AMMUNITION_CAPACITY_50PCT_MORE
	BRL_len_MINIMAL
	BRL_len_SHORT
	BRL_len_HANDGUN
	BRL_len_ASSAULT
	BRL_len_CARBINE
	BRL_len_RIFLE
	BRL_len_LONG
	BRL_len_VERY_LONG
	BRL_weight_HEAVY
	BRL_weight_STANDARD
	FRNTR_STOCKLESS
	FRNTR_STOCK_FOLDING
	FRNTR_STOCK_FULL
	FRNTR_MODULARIZATION
	FRNTR_BIPOD_ABSENT
	FRNTR_BIPOD_FIXED
	FRNTR_BIPOD_DETACHABLE
	FRNTR_SUPPORT_MOUNT
	ACSR_SUPPRESSOR_BASIC
	ACSR_SUPPRESSOR_STANDARD
	ACSR_SUPPRESSOR_EXTREME
	ACSR_AFD_MAGAZINE_FIXED
	ACSR_AFD_MAGAZINE_STANDARD
	ACSR_AFD_MAGAZINE_EXTENDED
	ACSR_AFD_MAGAZINE_DRUM
	ACSR_AFD_BELT
	ACSR_AFD_CLIPS
	ACSR_SCOPE_BASIC
	ACSR_SCOPE_LONG_RANGE
	ACSR_SCOPE_LOW_LIGHT
	ACSR_SCOPE_THERMAL
	ACSR_SCOPE_COMBINATION
	ACSR_SCOPE_MULTISPECTRAL
	ACSR_SCOPE_LASER_POINTER
	ACSR_SCOPE_ISS
	ACSR_SCOPE_HOLOGRAPHIC
	ACSR_ABSENT
	ACSR_OTHER_BAYONET_LUG
	ACSR_OTHER_BLING
	ACSR_OTHER_FLASHLIGHT
	ACSR_OTHER_GRAVITIC_SUPPORT
	ACSR_OTHER_GUN_CAMERA
	ACSR_OTHER_WEAPON_INTELLIGENT
	ACSR_OTHER_WEAPON_SECURE
	ACSR_OTHER_STABILISATION
	WRONG_INSTRUCTION
)

func Verbal(i int) string {
	switch i {
	case _UNDEFINED_:
		return "_UNDEFINED_"
	case RCVR_TYPE_HANDGUN:
		return "RCVR_TYPE_HANDGUN"
	case RCVR_TYPE_ASSAULT_WEAPON:
		return "RCVR_TYPE_ASSAULT_WEAPON"
	case RCVR_TYPE_LONGARM:
		return "RCVR_TYPE_LONGARM"
	case RCVR_TYPE_LIGHT_SUPPORT_WEAPON:
		return "RCVR_TYPE_LIGHT_SUPPORT_WEAPON"
	case RCVR_TYPE_HEAVY_WEAPON:
		return "RCVR_TYPE_HEAVY_WEAPON"
	case TECH_GAUSS_TECH:
		return "TECH_GAUSS_TECH"
	case TECH_ENERGY:
		return "TECH_ENERGY"
	case TECH_CONVENTIONAL:
		return "TECH_CONVENTIONAL"
	case CALLIBRE_HANDGUN_BlackPowder:
		return "CALLIBRE_HANDGUN_BlackPowder"
	case CALLIBRE_HANDGUN_Light:
		return "CALLIBRE_HANDGUN_Light"
	case CALLIBRE_HANDGUN_Medium:
		return "CALLIBRE_HANDGUN_Medium"
	case CALLIBRE_HANDGUN_Heavy:
		return "CALLIBRE_HANDGUN_Heavy"
	case CALLIBRE_SMOOTHBORES_Small:
		return "CALLIBRE_SMOOTHBORES_Small"
	case CALLIBRE_SMOOTHBORES_Light:
		return "CALLIBRE_SMOOTHBORES_Light"
	case CALLIBRE_SMOOTHBORES_Standard:
		return "CALLIBRE_SMOOTHBORES_Standard"
	case CALLIBRE_SMOOTHBORES_Heavy:
		return "CALLIBRE_SMOOTHBORES_Heavy"
	case CALLIBRE_LONGARM_BlackPowder:
		return "CALLIBRE_LONGARM_BlackPowder"
	case CALLIBRE_LONGARM_Rifle_Light:
		return "CALLIBRE_LONGARM_Rifle_Light"
	case CALLIBRE_LONGARM_Rifle_Intermediate:
		return "CALLIBRE_LONGARM_Rifle_Intermediate"
	case CALLIBRE_LONGARM_Rifle_Battle:
		return "CALLIBRE_LONGARM_Rifle_Battle"
	case CALLIBRE_LONGARM_Rifle_Heavy:
		return "CALLIBRE_LONGARM_Rifle_Heavy"
	case CALLIBRE_LONGARM_Rifle_AntiMaterial:
		return "CALLIBRE_LONGARM_Rifle_AntiMaterial"
	case CALLIBRE_LONGARM_Rifle_AntiMaterialHeavy:
		return "CALLIBRE_LONGARM_Rifle_AntiMaterialHeavy"
	case CALLIBRE_SNUB:
		return "CALLIBRE_SNUB"
	case CALLIBRE_Rocket:
		return "CALLIBRE_Rocket"
	case CALLIBRE_GAUSS_Standard:
		return "CALLIBRE_GAUSS_Standard"
	case CALLIBRE_GAUSS_Small:
		return "CALLIBRE_GAUSS_Small"
	case CALLIBRE_GAUSS_Enchanced:
		return "CALLIBRE_GAUSS_Enchanced"
	case CALLIBRE_GAUSS_Shotgun:
		return "CALLIBRE_GAUSS_Shotgun"
	case MECHANISM_SINGLE_SHOT:
		return "MECHANISM_SINGLE_SHOT"
	case MECHANISM_REPEATER:
		return "MECHANISM_REPEATER"
	case MECHANISM_SEMI_AUTOMATIC:
		return "MECHANISM_SEMI_AUTOMATIC"
	case MECHANISM_BURST_CAPABLE:
		return "MECHANISM_BURST_CAPABLE"
	case MECHANISM_FULLY_AUTOMATIC:
		return "MECHANISM_FULLY_AUTOMATIC"
	case MECHANISM_RAPID_FIRE:
		return "MECHANISM_RAPID_FIRE"
	case MECHANISM_VERY_RAPID_FIRE:
		return "MECHANISM_VERY_RAPID_FIRE"
	case MECHANISM_UNDERWATER:
		return "MECHANISM_UNDERWATER"
	case FEAT_func_ADVANCED_PROJECTILE_WEAPON:
		return "FEAT_func_ADVANCED_PROJECTILE_WEAPON"
	case FEAT_func_ACCUIRED:
		return "FEAT_func_ACCUIRED"
	case FEAT_func_BULLPUP:
		return "FEAT_func_BULLPUP"
	case FEAT_func_COMPACT:
		return "FEAT_func_COMPACT"
	case FEAT_func_COMPACT_VERY:
		return "FEAT_func_COMPACT_VERY"
	case FEAT_func_COOLING_SYSTEM_BASIC:
		return "FEAT_func_COOLING_SYSTEM_BASIC"
	case FEAT_func_COOLING_SYSTEM_ADVANCED:
		return "FEAT_func_COOLING_SYSTEM_ADVANCED"
	case FEAT_func_GUIDENCE_SYSTEM:
		return "FEAT_func_GUIDENCE_SYSTEM"
	case FEAT_func_HIGH_CAPACITY:
		return "FEAT_func_HIGH_CAPACITY"
	case FEAT_func_HIGH_QUALITY:
		return "FEAT_func_HIGH_QUALITY"
	case FEAT_func_INCREASED_RATE_OF_FIRE_1:
		return "FEAT_func_INCREASED_RATE_OF_FIRE_1"
	case FEAT_func_INCREASED_RATE_OF_FIRE_2:
		return "FEAT_func_INCREASED_RATE_OF_FIRE_2"
	case FEAT_func_INCREASED_RATE_OF_FIRE_3:
		return "FEAT_func_INCREASED_RATE_OF_FIRE_3"
	case FEAT_func_INCREASED_RATE_OF_FIRE_4:
		return "FEAT_func_INCREASED_RATE_OF_FIRE_4"
	case FEAT_func_INCREASED_RATE_OF_FIRE_5:
		return "FEAT_func_INCREASED_RATE_OF_FIRE_5"
	case FEAT_func_INCREASED_RATE_OF_FIRE_6:
		return "FEAT_func_INCREASED_RATE_OF_FIRE_6"
	case FEAT_func_LIGHTWEIGHT:
		return "FEAT_func_LIGHTWEIGHT"
	case FEAT_func_LIGHTWEIGHT_EXTREME:
		return "FEAT_func_LIGHTWEIGHT_EXTREME"
	case FEAT_func_LOW_QUALITY_1:
		return "FEAT_func_LOW_QUALITY_1"
	case FEAT_func_LOW_QUALITY_2:
		return "FEAT_func_LOW_QUALITY_2"
	case FEAT_func_LOW_QUALITY_3:
		return "FEAT_func_LOW_QUALITY_3"
	case FEAT_func_LOW_QUALITY_4:
		return "FEAT_func_LOW_QUALITY_4"
	case FEAT_func_LOW_QUALITY_5:
		return "FEAT_func_LOW_QUALITY_5"
	case FEAT_func_QUICKDRAW:
		return "FEAT_func_QUICKDRAW"
	case FEAT_func_RECOIL_COMPENSATION_1:
		return "FEAT_func_RECOIL_COMPENSATION_1"
	case FEAT_func_RECOIL_COMPENSATION_2:
		return "FEAT_func_RECOIL_COMPENSATION_2"
	case FEAT_func_RUGGED:
		return "FEAT_func_RUGGED"
	case FEAT_cap_ARMORED:
		return "FEAT_cap_ARMORED"
	case FEAT_cap_BULWARKED:
		return "FEAT_cap_BULWARKED"
	case FEAT_cap_DISGUISED:
		return "FEAT_cap_DISGUISED"
	case FEAT_cap_STEALTH_BASIC:
		return "FEAT_cap_STEALTH_BASIC"
	case FEAT_cap_STEALTH_EXTREME:
		return "FEAT_cap_STEALTH_EXTREME"
	case FEAT_cap_VACUUM:
		return "FEAT_cap_VACUUM"
	case AMMUNITION_CAPACITY_50PCT_LESS:
		return "AMMUNITION_CAPACITY_50PCT_LESS"
	case AMMUNITION_CAPACITY_40PCT_LESS:
		return "AMMUNITION_CAPACITY_40PCT_LESS"
	case AMMUNITION_CAPACITY_30PCT_LESS:
		return "AMMUNITION_CAPACITY_30PCT_LESS"
	case AMMUNITION_CAPACITY_20PCT_LESS:
		return "AMMUNITION_CAPACITY_20PCT_LESS"
	case AMMUNITION_CAPACITY_10PCT_LESS:
		return "AMMUNITION_CAPACITY_10PCT_LESS"
	case AMMUNITION_CAPACITY_STANDARD:
		return "AMMUNITION_CAPACITY_STANDARD"
	case AMMUNITION_CAPACITY_10PCT_MORE:
		return "AMMUNITION_CAPACITY_10PCT_MORE"
	case AMMUNITION_CAPACITY_20PCT_MORE:
		return "AMMUNITION_CAPACITY_20PCT_MORE"
	case AMMUNITION_CAPACITY_30PCT_MORE:
		return "AMMUNITION_CAPACITY_30PCT_MORE"
	case AMMUNITION_CAPACITY_40PCT_MORE:
		return "AMMUNITION_CAPACITY_40PCT_MORE"
	case AMMUNITION_CAPACITY_50PCT_MORE:
		return "AMMUNITION_CAPACITY_50PCT_MORE"
	case BRL_len_MINIMAL:
		return "BRL_len_MINIMAL"
	case BRL_len_SHORT:
		return "BRL_len_SHORT"
	case BRL_len_HANDGUN:
		return "BRL_len_HANDGUN"
	case BRL_len_ASSAULT:
		return "BRL_len_ASSAULT"
	case BRL_len_CARBINE:
		return "BRL_len_CARBINE"
	case BRL_len_RIFLE:
		return "BRL_len_RIFLE"
	case BRL_len_LONG:
		return "BRL_len_LONG"
	case BRL_len_VERY_LONG:
		return "BRL_len_VERY_LONG"
	case BRL_weight_HEAVY:
		return "BRL_weight_HEAVY"
	case BRL_weight_STANDARD:
		return "BRL_weight_STANDARD"
	case FRNTR_STOCKLESS:
		return "FRNTR_STOCKLESS"
	case FRNTR_STOCK_FOLDING:
		return "FRNTR_STOCK_FOLDING"
	case FRNTR_STOCK_FULL:
		return "FRNTR_STOCK_FULL"
	case FRNTR_MODULARIZATION:
		return "FRNTR_MODULARIZATION"
	case FRNTR_BIPOD_ABSENT:
		return "FRNTR_BIPOD_ABSENT"
	case FRNTR_BIPOD_FIXED:
		return "FRNTR_BIPOD_FIXED"
	case FRNTR_BIPOD_DETACHABLE:
		return "FRNTR_BIPOD_DETACHABLE"
	case FRNTR_SUPPORT_MOUNT:
		return "FRNTR_SUPPORT_MOUNT"
	case ACSR_SUPPRESSOR_BASIC:
		return "ACSR_SUPPRESSOR_BASIC"
	case ACSR_SUPPRESSOR_STANDARD:
		return "ACSR_SUPPRESSOR_STANDARD"
	case ACSR_SUPPRESSOR_EXTREME:
		return "ACSR_SUPPRESSOR_EXTREME"
	case ACSR_AFD_MAGAZINE_FIXED:
		return "ACSR_AFD_MAGAZINE_FIXED"
	case ACSR_AFD_MAGAZINE_STANDARD:
		return "ACSR_AFD_MAGAZINE_STANDARD"
	case ACSR_AFD_MAGAZINE_EXTENDED:
		return "ACSR_AFD_MAGAZINE_EXTENDED"
	case ACSR_AFD_MAGAZINE_DRUM:
		return "ACSR_AFD_MAGAZINE_DRUM"
	case ACSR_AFD_BELT:
		return "ACSR_AFD_BELT"
	case ACSR_AFD_CLIPS:
		return "ACSR_AFD_CLIPS"
	case ACSR_SCOPE_BASIC:
		return "ACSR_SCOPE_BASIC"
	case ACSR_SCOPE_LONG_RANGE:
		return "ACSR_SCOPE_LONG_RANGE"
	case ACSR_SCOPE_LOW_LIGHT:
		return "ACSR_SCOPE_LOW_LIGHT"
	case ACSR_SCOPE_THERMAL:
		return "ACSR_SCOPE_THERMAL"
	case ACSR_SCOPE_COMBINATION:
		return "ACSR_SCOPE_COMBINATION"
	case ACSR_SCOPE_MULTISPECTRAL:
		return "ACSR_SCOPE_MULTISPECTRAL"
	case ACSR_SCOPE_LASER_POINTER:
		return "ACSR_SCOPE_LASER_POINTER"
	case ACSR_SCOPE_ISS:
		return "ACSR_SCOPE_ISS"
	case ACSR_SCOPE_HOLOGRAPHIC:
		return "ACSR_SCOPE_HOLOGRAPHIC"
	case ACSR_ABSENT:
		return "ACSR_ABSENT"
	case ACSR_OTHER_BAYONET_LUG:
		return "ACSR_OTHER_BAYONET_LUG"
	case ACSR_OTHER_BLING:
		return "ACSR_OTHER_BLING"
	case ACSR_OTHER_FLASHLIGHT:
		return "ACSR_OTHER_FLASHLIGHT"
	case ACSR_OTHER_GRAVITIC_SUPPORT:
		return "ACSR_OTHER_GRAVITIC_SUPPORT"
	case ACSR_OTHER_GUN_CAMERA:
		return "ACSR_OTHER_GUN_CAMERA"
	case ACSR_OTHER_WEAPON_INTELLIGENT:
		return "ACSR_OTHER_WEAPON_INTELLIGENT"
	case ACSR_OTHER_WEAPON_SECURE:
		return "ACSR_OTHER_WEAPON_SECURE"
	case ACSR_OTHER_STABILISATION:
		return "ACSR_OTHER_STABILISATION"
	case WRONG_INSTRUCTION:
		return "WRONG_INSTRUCTION"
	}
	return "MUST NOT APPEAR"
}
